services:
  redis:
    image: redis:6.2-buster
    ports:
      - "${REDIS_PORT:-6380}:6379"
  postgres:
    image: postgres:14.2
    ports:
      - "${DATABASE_PORT:-5433}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
volumes:
  db-data:
    driver: local
